Obliquity model - Issue 34
Bramson-Planetary-Research-Group/Mars-Troughs pull request #35
Opened 2021-05-26 16:07 UTC by klaferr

- Added a linear model that uses obliquity instead of insolation in accumulation model
- added tests to related file
- added a statement into trough.py to input the right values for obliquity instead of insolation 
- updated test notebook to show the result of using obliquity dependence

I also added a new file for obliquity which is what I interpreted as the time steps since the original obliquity.txt file did not contain the time steps.

2021-05-27 03:11 UTC, tmcclintock requested changes
Looks great so far. Just a few minor things.

Also, can you add another test to `test_trough.py` where we instantiate a `Trough` with an obliquity model? We should just make sure it all works OK.

2021-05-27 03:11 UTC, tmcclintock commented on mars_troughs/data/Obliquity_new.txt
> +Obliquity (units?) Time(yrs)
I'm pretty sure the units of obliquity are degrees. You should double check with @ambramson on this though and also what the times are. @ambramson made the original obliquity text file.

2021-06-04 15:33 UTC, klaferr commented
With new pushes:
 - moved get_accumulation_at_t to timedependentmodel
 - fixed docstrings
- fixed naming scheme for model
- added optional type for model names in trough.py
- fixed obliquity file header
I wasn't sure what you wanted by a test for the obliquity model but I added a test that I think test the set up of an obliquity model-based trough

2021-06-04 15:56 UTC, tmcclintock commented
@klaferr looks great to me. Nice job! Feel free to merge to main.

2021-06-04 16:06 UTC, merged